server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:socialdb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:social}
    password: ${MYSQL_PASSWORD:social}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

flyway:
  enabled: true
  locations: classpath:db/migration
