services:
  mysql:
    image: mysql:8.0
    env_file: .env
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: maven:3.9-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./backend/social-app:/app
      - maven-repo:/root/.m2
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST:-mysql}
    command: mvn -DskipTests spring-boot:run
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-8081}:8081"

  adminer:
    image: adminer:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${ADMINER_PORT:-8080}:8080"

volumes:
  dbdata:
  maven-repo: